{% set version = "0.7.10" %}

package:
  name: cis_interface
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cis_interface/cis_interface-{{ version }}.tar.gz
  sha256: 4ee72fa2418f9d040085225193a4adfa4de84b03776b6d28768bbcd31698fdbe
  
build:
  number: 1004
  skip: true  # [win and vc<14]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - czmq
    - sysv_ipc  # [not win]
    - zeromq
  run:
    - python
    - cerberus
    - czmq
    - jsonschema
    - matplotlib-base
    - numpy
    - pandas
    - pint  # [py2k]
    - psutil
    - pystache
    - python-rapidjson  # [not py2k]
    - pyyaml
    - pyzmq
    - scipy
    - sysv_ipc  # [not win]
    - unyt  # [not py2k]
    - zeromq
    - perf

test:
  imports:
    - cis_interface

about:
  home: https://github.com/cropsinsilico/yggdrasil/tree/cis_interface
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A framework for connecting computational models from multiple languages.'

  description: |
    The Crops in Silico (CiS) framework, cis_interface, provides support for
    connecting scientific models written in different programming languages.
    To connect two models, modelers add communications interfaces to the model code
    and provide declarative specification files that identfy the
    models that should be run and the inputs and outputs those models
    expect. cis_interface uses this information to launch the models
    on parallel processes and orchestrate asynchronous communication between them.
    Although designed for connecting crop models, cis_interface can be used to
    connect scientific models from any domain.
  doc_url: https://cropsinsilico.github.io/cis_interface
  dev_url: https://github.com/cropsinsilico/yggdrasil

extra:
  recipe-maintainers:
    - langmm
