{% set name = "cis_interface" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e0870513666311b30615b59d14c25fdcf0fff9dc4da0e7f50203ddb10963127

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - czmq
    - pip
    - python
    - sysv_ipc  # [unix]
    - zeromq
  run:
    - cerberus
    - czmq
    - jsonschema
    - matplotlib
    - nose
    - numpy
    - pandas
    - pint
    - psutil
    - pystache
    - python
    - pyyaml
    - pyzmq
    - scipy
    - sysv_ipc  # [unix]
    - unyt
    - zeromq
    - perf

test:
  imports:
    - cis_interface
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - astropy
    - nose
    - pika
    - cmake
    - valgrind  # [unix]
  commands:
    - cistest --nologcapture -svx

about:
  home: https://github.com/cropsinsilico/yggdrasil
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A framework for connecting computational models from multiple languages.'

  description: |
    The CiS framework provides support for connecting scientific models
    written in different programming languages. To connect two models,
    modelers add communications interfaces to the model code
    and provide declarative specification files that identfy the
    models that should be run and the inputs and outputs those models
    expect. The CiS framework uses this information to launch the models
    on parallel processes and orchestrate communication between them. NOTE:
    Following this release, the cis_interface package will be renamed to
    yggdrasil. This release and its accompanying docs will be maintained
    under the name cis_interface, but will not receive future updates.
  doc_url: https://cropsinsilico.github.io/cis_interface
  dev_url: https://github.com/cropsinsilico/yggdrasil

extra:
  recipe-maintainers:
    - langmm
