travis:
  secure:
    BINSTAR_TOKEN: LlrbapsLsjI9XUs4kMMbumVYiAFBvdrz61n+gUvsDBfksS1aI6b3gHd7H+ez5ORAIQBKJa1yY3CE+dylqODiij8iBnW4Y499USIs+g04BGbans5VmFjJqhbJP/PL2JqAaeuZL0AH5SR5VUM+9aqP5XC72EiPYKbJp60LYPPlsKvMpm6RzOfEXThBwfCQUznXNPesBvx8yYAIw4wtKk4dGzIG9/eJpqKzxb3vJJsvRfBksW53ZsEYKM/3ryJlpRUq+TyIdgvMW+KaX+0wcWIP4aDnv6AAW9wSYrQlktHaLdaDBSloeKV55MeZLsBYyO2bFkklEeV3AFEAUY8CPEWJh+DawaFocuBg4isXnYmMDu0tLYyGeC5cIKDu9+7C+t7g4P2/AUo2SfCgoSeyX4RDRvMm8W2Shf//tTE3w6jv1ORqyeIqUstXD1Zlw0/wXUWhoI2Db6yUVtyFM9zTaiH2g9MTBZh9c9wyjzUNtdUs/MneQaOeJzGbi0eDdGyhS93i3EDdaYPYbn/eU/hnwR8jnRAxiNILf8FamoN8U4TU1q/rA6vuEiLM9wufsAaWhYkmho4ANbCG9tXkSqm+XQ4WbvV9hVQqYkirl4sSHjAAStmkLIo1MhxpoPo9F1NV9itqIkakUXuIMuUTMEgdxKU8w15VwLkOsGr9DucjftjLGPo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
